export {default as Latest} from './latest/latest'
export {default as Seclast} from './latest/seclat'
export {default as Editor} from './editor/editor'
export {default as Entert} from './entert/entert'
export {default as Footer} from './footer/footer'
// export {default as Header} from './header/header'
export {default as Sport} from './sport/sport'
export {default as VideFile} from './vid/vid'
export {default as Travel} from './travel/travel'
export {default as Business} from './business/business'